### ISSUE TITLE
下周岗位

### ISSUE THREAD

**Issue by HeadhunterClaire** [HeadhunterClaire/toMyDearCandidate#3]
#### 2016年 第3周 前端急招岗位 整理时间：1月16日 星期六     

<table class="table table-bordered table-striped table-condensed">
   <tr>
      <th>地点</th>
      <th>公司规模</th>
      <th>招聘岗位</th>
      <th>岗位职责及任职要求</th>
   </tr>
   <tr>
      <td>上海徐汇</td>
      <td>已上市</td>
      <td>资深前端</td>
      <td>熟练掌握JavaScript、HTML5、CSS3，学习能力强，能跟着架构师快速学习先进前端开发框架</td>
   </tr>
   <tr>
      <td>上海徐汇</td>
      <td>已上市</td>
      <td>前端</td>
      <td>3年↑，能熟练运用HTML5、CSS进行合理的PC端网页制作和构建移动端WebApp</td>
   </tr>
   <tr>
      <td>上海浦东</td>
      <td>已上市</td>
      <td>前端</td>
      <td>2年↑，熟练掌握JavaScript、HTML、CSS，WebApp方向，需熟悉后端.Net及数据库SQL语言</td>
   </tr>
   <tr>
      <td>上海闸北</td>
      <td>A轮</td>
      <td>前端</td>
      <td>熟练掌握JavaScript、HTML、CSS，熟悉前端性能优化，有移动设备的应用开发经验优先</td>
   </tr>
   <tr>
      <td>北京海淀</td>
      <td>成熟型</td>
      <td>前端</td>
      <td>计算机相关专业优先，熟练掌握JavaScript、HTML5、CSS3，负责公司产品页面开发、维护、改进和优化</td>
   </tr>
   <tr>
      <td>北京海淀</td>
      <td>成长期</td>
      <td>前端</td>
      <td>3年↑，精通Javascript，能灵活使用DIV+CSS+JavaScript手写代码，手机端开发经验丰富者优先</td>
   </tr>
   <tr>
      <td>北京朝阳</td>
      <td>B轮</td>
      <td>前端</td>
      <td>精通JavaScript、HTML5、CSS3，熟悉常用前端开发框架，有PhoneGap等移动跨平台中间件使用经验优先</td>
   </tr>
   <tr>
      <td>广州天河</td>
      <td>C轮</td>
      <td>资深前端</td>
      <td>负责移动端App产品的H5页面开发，精通JavaScript、CSS和HTML5，有大型网站、客户端开发经验优先</td>
   </tr>
   <tr>
      <td>广州荔湾</td>
      <td>成熟型</td>
      <td>前端</td>
      <td>精通JavaScript，熟练使用jQuery、Bootstrap、Angular、Ember、YUI等，有大流量网站开发经验优先</td>
   </tr>
   <tr>
      <td>深圳南山</td>
      <td>A轮</td>
      <td>前端</td>
      <td>2年↑，计算机相关专业，精通JavaScript、HTML、CSS，熟悉常用前端开发框架</td>
   </tr>
   <tr>
      <td>深圳南山</td>
      <td>A轮</td>
      <td>资深前端</td>
      <td>3年↑，需要带团队，精通JavaScript、CSS、HTML，具有极客精神</td>
   </tr>
   <tr>
      <td>深圳南山</td>
      <td>成熟型</td>
      <td>前端</td>
      <td>2年↑，负责公司电商平台的前端开发，有大用户量访问网站页面优化经验优先</td>
   </tr>
   <tr>
      <td>杭州</td>
      <td>D轮（分公司）</td>
      <td>前端架构</td>
      <td>精通OOP思想，熟练掌握前端模块化开发，精通至少一个落地框架，熟悉HybridApp，熟悉一门后端语言</td>
   </tr>
   <tr>
      <td>杭州</td>
      <td>D轮</td>
      <td>资深前端</td>
      <td>技术点：ES6、NodeJS、HTML5、RequireJS、jQuery、Grunt、Gulp、Webpack、ReactJS、Zepto</td>
   </tr>
   <tr>
      <td>南京</td>
      <td>研发中心</td>
      <td>Web引擎研发</td>
      <td>负责嵌入式浏览器内核(Webkit和Google Blink)开发、优化，熟悉C/C++和HTML/CSS/JavaScript</td>
   </tr>
   <tr>
      <td>郑州</td>
      <td>研发中心</td>
      <td>前端</td>
      <td>熟悉Web前端技术：JavaScript、CSS、语义化标签、Canvas 、HTML5等</td>
   </tr>
   <tr>
      <td>西安</td>
      <td>B轮（分公司）</td>
      <td>前端</td>
      <td>2年↑，精通JavaScript，熟练使用AngularJS、Ionic等常用框架，有iOS、Android开发经验优先</td>
   </tr>
<tr>
      <td>武汉</td>
      <td>集团公司</td>
      <td>前端</td>
      <td>熟练掌握JavaScript，对浏览器兼容性、代码可维护、前端性能优化有深刻体会，会NodeJS优先</td>
   </tr>
<tr>
      <td>武汉</td>
      <td>研发中心</td>
      <td>资深前端</td>
      <td>2年↑，精通JavaScript/HTML/CSS，熟练使用AngularJS、Backbone等常用框架，熟悉Python、NodeJS或PHP优先</td>
   </tr> 
</table>

***
#### 说明:
- 所列岗位全部要人，有意请与我联系沟通职位详情。
- 正在做武汉前端行业Full Mapping（猎头术语解释：指特定地区、行业的目标人才地毯式搜索，猎头杀手锏之一）。随着一线城市用人成本增加，不少企业将其研发基地转移，武汉拥有九省通衢的地理位置和大学城提供的丰富人才储备，是最好的选择之一。我是一枚深信互联网会为二线省会城市带来发展机遇并且努力成为其发展促进作用的猎头，先打好武汉基础，关注家乡互联网发展的朋友们欢迎与我交流^_^
<br>
重点操作以下两个岗位：
<table class="table table-bordered table-striped table-condensed">
   <tr>
      <th>工作地点</th>
      <th>公司类型</th>
      <th>岗位Title</th>
      <th>岗位职责及任职要求</th>
   </tr>
<tr>
      <td>沌口</td>
      <td>本土集团公司，现有13个分公司，2015年营业额30亿，传统行业把业务搬到线上来做电商平台</td>
      <td>前端</td>
      <td>熟练掌握JavaScript，对浏览器兼容性、代码可维护、前端性能优化有深刻体会，会NodeJS优先</td>
   </tr>
<tr>
      <td>珞瑜路</td>
      <td>北京公司在武汉的研发中心，有自主研发的产品，有单独的前端团队，技术氛围较开放</td>
      <td>资深前端</td>
      <td>2年↑，精通JavaScript/HTML/CSS，熟练使用AngularJS、Backbone等常用框架，熟悉Python、NodeJS或PHP优先</td>
   </tr>
</table>

- 欢迎加我微信：itclaire，请附上简单自我介绍哦。

<br>

#### 关于转介绍:
- 我的候选人中，正在高速增长的是朋友的转介绍，非常感谢大家的支持。您可以把我的联系方式发给您的前端朋友，让TA来联系我；**也欢迎直接向我推荐，只需告知我您朋友的基本情况和联系方式即可，其它的事情都交给我。**我在和TA联系时，会说是朋友介绍，不会告知具体来源，一方面您能帮忙推荐已经非常感激，另一方面猎头工作有专业的流程和保密措施，这也是为了保护候选人隐私。 隐私保护是作为猎头的基本职业道德，也是我在工作中最注意的一点，我会严格保守和候选人沟通过程中了解到的所有信息，请朋友们放心。

***

######  贺帆Claire｜ 专注、敬业的前端猎头｜ 猎上网签约顾问
[微信](https://ooo.0o0.ooo/2016/01/02/56887f43e5f8e.jpg)[ ● 微博](http://weibo.com/itclaire)[ ● 领英](http://www.linkedin.com/in/itclaire)[ ● 猎聘](http://www.liepin.com/LT20586292/)[ ● 知乎](https://www.zhihu.com/people/frontendoffer)[ ● SegmentFault](http://segmentfault.com/u/itclaire)[ ● Twitter](https://twitter.com/frontendoffer)[ ● Quora](https://www.quora.com/profile/ITClaire)[ ● QQ ● ](http://sighttp.qq.com/authd?IDKEY=81f15352d48ad819e1da07def9bbffe023189c1a603472fe)<FrontEndOffer@foxmail.com>

**Comment by HeadhunterClaire** [comment]
测试一下字体   **粗体**    *斜体*

**Comment by Alexis374** [comment]
写上薪资水平啊

**Comment by FrankFang** [comment]
对，不写薪资范围很浪费时间的。也没啥吸引力。

**Comment by Wellaiyo** [comment]
还有公司行业也很重要，完全可以多透漏点信息的，求职的人又不会跳过你直接去找公司

**Comment by HeadhunterClaire** [comment]
*很感谢大家留言，刚好有些想表达的，借这个机会一并写出来。 ^_^o ~~~*
*很喜欢这种直接的建议，以后还请多多批评指教 (^人^)  ，一起进步！*


对的，非常赞同，若考虑跳槽去新公司，不知道薪酬范围很浪费时间，薪酬是衡量新公司的重要指标，也是个人价值的一个体现。不过，我在这里整理急招岗位与一般HR发出的招聘需求是不一样的，首先数量上，HR只有自己一家公司，我是实时招聘的十余家企业；其次目的上，**我把这当成和前端朋友们的一个长期互动，我希望大家能通过急招岗位对我的业务范围能实时进行了解，并且能通过阅读这些信息有所收获。**至于岗位推荐，猎头服务是一个一对一的，我只为企业推荐我熟悉的候选人，当手上的候选人在考虑新机会时，我给的职位是通过之前沟通精准推荐的具体企业，是要针对岗位和候选人做非常详细沟通的。

###### 回到急招岗位，几点说明：
- 想突出［岗位职责及任职要求］，希望让哪怕现在不考虑跳槽的前端朋友们看到也能收获一定参考价值，至少希望在看我整理的岗位时，关注点还是在技术，联想的是猎头能够带来事业上的助力，而非浮于表面的一个跳槽途径。
- 若有朋友考虑新机会，请发送简历到我的邮箱，我会根据您的求职意愿做详细沟通。暂时不考虑新机会也可以发送简历过来，未雨绸缪。在合适时间里，当您可能感兴趣的企业有招聘需求时，我会和您沟通您对这家企业的看法，经过您的同意后，需要写一份类似于简历的详细推荐报告给企业，企业若觉得合适就会安排约见面试，我会提供面试辅导，若面试没有通过，我会给您反馈，若通过，会和您配合进行之后的薪资谈判，以及陪伴您度过离入职特殊时期。
- 不写薪资的原因：如上说明，这份急招岗位是为了突出整体价值，不是为了单个企业的招聘，有的时候过多信息反而显得浮躁，是干扰。


###### 可能有些正准备跳槽的朋友会比较关心，关于薪资多谈几点：
- **薪资范围：**这点我在推荐时就已经风险预控了，我能拿来和您沟通的岗位一定是包括薪资各方面您会感兴趣的。
- **薪资谈判：**企业在没有充分认识到您的潜力和实力时，就给薪资定位是不利于之后谈判的；同样，您在没有充分了解企业情况时，就给薪资期待，说高了说低了都很不好。一个好的薪资谈判核心在于，是在最后见决策者的时候来敲定。这个时候才是可以做决定的人在了解了充分信息后达成的一致。若资历浅的HR在早期沟通就问薪资期望，您可以绕过去：“相信企业会根据我的实力，提供双方都满意的薪资”，也可以说：“薪资方面的考虑已经和猎头沟通好了”，来给自己留下足够空间。
- **我的立场：**您的身价，我的饭碗。从利益角度，我也会为您争取最高薪酬。


@Alexis374 感谢您的建议！(^人^)
@FrankFang 同样感谢！(^人^)
@Wellaiyo 对的对的，没啥好藏着捏着的，除了少数企业特别交待的保密职位，我的候选人在被推荐之前肯定知道企业名字的哈。:wink:

**Comment by iammecn** [comment]
写这么多不容易，支持下

**Comment by HeadhunterClaire** [comment]
@iammecn 谢谢！以后在一个圈子里，还请多多照顾和指教^_^o ~~~

**Comment by magicismight** [comment]
用github的猎头，头一次见，也是够拼的.

**Comment by HeadhunterClaire** [comment]
@magicismight 哈哈 谢谢鼓励！

新开博客，欢迎多多指教: [HeadhunterClaire'Blog](http://clairevip.com)，[匿名调查](http://www.sojump.com/jq/7050740.aspx)。

以后职位更新将发布在博客上，本issue关闭 ：）

欢迎提交新issue留言。
