### ISSUE TITLE
Typo found

### ISSUE THREAD

**Issue by JohnWong** [HeadhunterClaire/toMyDearCandidate#4]
项目简介里的`companiese`应该是`companies`

I am a dedicated headhunter who focused on recruiting front-end developers for IT companiese in China.

**Comment by amio** [comment]
貌似已经修正了

ping @HeadhunterClaire 来点下 “Close Issue” 按钮 ;-)

**Comment by HeadhunterClaire** [comment]
@amio  哈哈 好的 新技能Get (o^^o) 
@JohnWong  非常感谢，以后还请多多指教！
